### ISSUE TITLE
[feature request] Unicode confusable characters data

### ISSUE THREAD

**Issue by garywill** [tonton-pixel/unicopedia-plus#13]
Hi @tonton-pixel ,
Thank you for this amazing tool!

What about adding this as new feature, like this, Unicode official Utilitie: Confusables https://util.unicode.org/UnicodeJsps/confusables.jsp?a=%E5%9C%9F%E5%B7%A5%E4%B8%80%E4%BA%8C%E4%BA%BA%E4%B9%99%E5%85%AB%E5%8D%81&r=None

Already some third-party tools:
- (already on npm) https://github.com/michaelficarra/unicode-confusables-data
- (in Ruby) https://github.com/janlelis/unicode-confusable

**Comment by tonton-pixel** [comment]
Hi @garywill,
Thanks for your kind words of appreciation!

This feature request is definitely a useful utility to add to the application, especially since concerns about security related to the abuse of Unicode characters have been increasing recently.

I'm currently busy working on my other app [Unicopedia Sinica](https://github.com/tonton-pixel/unicopedia-sinica), but I'm indeed planning to add such a feature as soon as I can. Thanks for your helpful links too!

--Michel
