### ISSUE TITLE
Win32 won't build correctly?

### ISSUE THREAD

**Issue by 747** [tonton-pixel/unicopedia-plus#3]
```
PS C:\Users\<User>\unicopedia-plus> npm run build-win32

> unicopedia-plus@6.2.2 build-win32 C:\Users\<User>\unicopedia-plus
> electron-packager . --asar --out=build --platform=win32 --ignore=/~.* --ignore=^/screenshots --ico
n=icons/icon.ico --overwrite

Packaging app for platform win32 x64 using electron v7.1.9
Wrote new app to build\Unicopedia Plus-win32-x64
```

**Double click the exe**: nothing pops out
**Double click again**:
![image](https://user-images.githubusercontent.com/3427854/72707392-a6101000-3ba3-11ea-8549-1606ed7d3fa2.png)

---
```
PS C:\Users\<User>\unicopedia-plus> npm start

> unicopedia-plus@6.2.2 start C:\Users\<User>\unicopedia-plus
> electron .
```
![image](https://user-images.githubusercontent.com/3427854/72707487-d657ae80-3ba3-11ea-91ff-dee141e75b03.png)

**Comment by tonton-pixel** [comment]
Thanks for your bug report.

Your description is definitely helpful. Unfortunately, I cannot reproduce the issue since the only platforms I have access to are macOS and Linux (Mint and Ubuntu in a VM), and I've never tested the application under win32 myself.

Since the main window can get succesfully displayed, although empty, with its icon and menubar, I think the build instructions for win32 are okay, and that a problem arises when the renderer process code is executed, but only in build/packaged mode.

In the window menubar, when this happens, could you select the `Toggle Developer Tools` menu item of the `Developer` menu, and copy-paste the full error message which gets probably (hopefully!) logged in red in the DevTools console. That would be the best for me if you can post it...

As for why the window shows up only the second time the .exe icon is double-clicked, I guess it has to do with the "single instance" mechanism that is implemented in the main process, which prevents the opening of a new window as a second instance, and substitutes a call to show the existing window instead, even if its contents are not ready.

**Comment by 747** [comment]
Hi, below is the error output (the reported location is `electron/js2c/asar.js:548`):
```
Uncaught Error: ENOENT, renderer\lib\unicode\CLDR\annotations\en.xml not found in C:\Users\<User>\unicopedia-plus\build\Unicopedia Plus-win32-x64\resources\app.asar
    at createError (electron/js2c/asar.js:111)
    at Object.fs.readFileSync (electron/js2c/asar.js:548)
    at getAnnotations (C:\Users\<User>\unicopedia-plus\build\Unicopedia Plus-win32-x64\resources\app.asar\renderer\lib\unicode\get-cldr-annotations.js:37)
    at module.exports (C:\Users\<User>\unicopedia-plus\build\Unicopedia Plus-win32-x64\resources\app.asar\renderer\lib\unicode\get-cldr-annotations.js:67)
    at Object.module.exports.start (C:\Users\<User>\unicopedia-plus\build\Unicopedia Plus-win32-x64\resources\app.asar\renderer\units\Emoji Data Finder\import.js:131)
    at Object.<anonymous> (C:\Users\<User>\unicopedia-plus\build\Unicopedia Plus-win32-x64\resources\app.asar\renderer\renderer.js:458)
    at Object.<anonymous> (C:\Users\<User>\unicopedia-plus\build\Unicopedia Plus-win32-x64\resources\app.asar\renderer\renderer.js:592)
    at Module._compile (internal/modules/cjs/loader.js:880)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892)
    at Module.load (internal/modules/cjs/loader.js:735)
```

**Comment by tonton-pixel** [comment]
Hi,

Thanks for the error output. It's quite odd indeed: the `en.xml` file location looks valid to me.
But maybe there is some conflict between slash and backslash characters used in file paths, at least when resources are extracted from an asar-compressed archive.

Since you reported that the unpackaged application run by `npm start` appears to launch correctly, I guess that the problem could be temporarily solved by removing the `--asar` flag from the `build-win32` script, i.e., in the `package.json` file, replace the line:

    "build-win32": "electron-packager . --asar --out=build --platform=win32 --ignore=/~.* --ignore=^/screenshots --icon=icons/icon.ico --overwrite",

with :

    "build-win32": "electron-packager . --out=build --platform=win32 --ignore=/~.* --ignore=^/screenshots --icon=icons/icon.ico --overwrite",

then, run `npm run build-win32` again, and see what happens when double-clicking the newly generated .exe file icon (be sure that no instance of the application is already running before doing that). Note that it may take longer than usual to launch the packaged application the very first time, but in any case, it should take more than 10 seconds anyway.

Please let me know of the result.

**Comment by 747** [comment]
Thank you! It worked as you said and seems to run normally the same way as `npm start` does now.

**Comment by 747** [comment]
FWIW I found in the unpacked resources that a directory name in the middle of path to `en.xml` is `cldr` rather than the upper-case `CLDR`.

**Comment by tonton-pixel** [comment]
I'm glad to know that it works with the temporary fix.

Thanks also for your findings about unexpected case folding of path components, this is very helpful. I'll do more investigations on the issue from now on...
BTW, in order to get more precise information about your OS and understand which influence it may have on this case issue,  I would appreciate if you could select the `Copy System Info to Clipboard` command from the app's `Developer` menu, and post me its contents.

**Comment by 747** [comment]
Here is the requested data:
```
-- Application --

Name: Unicopedia Plus
Version: 6.2.2
Date: 2020-01-22T02:30:49.423Z

Locale: ja
Packaged: true

-- Framework --

System Version: 10.0.18363
Platform: win32
Architecture: x64
Default App: false
Mac App Store App: false
Windows Store App: false
Electron Version: 7.1.9
Node Version: 12.8.1
V8 Version: 7.8.279.23-electron.0
Chromium Version: 78.0.3904.130
ICU Version: 64.2
Unicode Version: 12.1

-- Operating System --

OS Type: Windows_NT
OS Platform: win32
OS Release: 10.0.18363
CPU Architecture: x64
CPU Endianness: LE
CPU Logical Cores: 4
CPU Model: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
CPU Speed (MHz): 2904
```

**Comment by tonton-pixel** [comment]
Hi,

> FWIW I found in the unpacked resources that a directory name in the middle of path to en.xml is cldr rather than the upper-case CLDR.

That's it! The bug was indeed on my side (although not directly) and, fortunately, pretty easy to fix.

Without your help, I guess I would never have thought of a typo in the directory name on the *GitHub* repository.

You see, the name of the directory is `CLDR` on my *local* repository, but `cldr` on my *GitHub* repository (for some reason I don't recall) and I was assuming that the two repositories would always be correctly kept in sync after clicking on the VSCode's built-in button whose tooltip is `Unicopedia Plus (Git) - Synchronize Changes`, but I was wrong, of course: case matters!

The latest release `6.3.0` should fix the issue, and for all platforms...

Thank you very much for your collaboration.

Best regards,

-- Michel
